name: Help_Documentation.

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

    paths:
     - .github/workflows/main.yml
     
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Install pychm Python package
        run: |
          python -m pip install --upgrade pip
          python -m pip install pychm
        shell: cmd

      - name: Convert HHP to CHM using Python
        run: python convert_to_chm.py
        shell: cmd

      - name: Upload CHM file
        uses: actions/upload-artifact@v3
        with:
          name: VCollabPro-CHM
          path: VCollabPro.chm  
