name: Help_Documentation.

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

    paths:
     - .github/workflows/main.yml
     
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Create directory
        run: |
             mkdir HelpDocument
                    
      - uses: actions/setup-python@v2
        with:
         python-version: '3.6' 
              
      - name: Install Sphinx
        run: |
          python -m pip install --upgrade pip
          pip install -U sphinx
          pip install -U sphinx sphinxcontrib-video sphinx_rtd_theme myst-parser sphinx_bootstrap_theme

      - name: Run make.bat from prox build documentation
        run: |
          .\make.bat htmlhelp
          
      - name: List files
        run: |
             cd build
             dir

      - name: List files
        run: |
             cd build
             dir htmlhelp
             
             
      - name: install hhw
        run: |
              choco install html-help-workshop -y

      - name: Compile CHM Help File
        run: |
             cd build\htmlhelp
             dir
             if (Test-Path "D:\a\prohelpdoc\prohelpdoc\build\htmlhelp\VCollabPro.hhp") {
               & "C:\Program Files (x86)\HTML Help Workshop\hhc.exe" "D:\a\prohelpdoc\prohelpdoc\build\htmlhelp\VCollabPro.hhp"
               } else {
               Write-Host "File not found!"
               exit 1
              }
             
      - name: List files
        run: |
             cd build
             dir htmlhelp      


     
     # - name: Verify file exists and convert
     #   run: |
     #         if (Test-Path "D:\a\prohelpdoc\prohelpdoc\build\htmlhelp\VCollabPro.hhp") {
     #          & "C:\Program Files (x86)\HTML Help Workshop\hhc.exe" "D:\a\prohelpdoc\prohelpdoc\build\htmlhelp\VCollabPro.hhp"
     #          } else {
     #          Write-Host "File not found!"
     #          exit 1
     #         }
