name: Help_Documentation.

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

    paths:
     - .github/workflows/main.yml
     
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install the older Chocolatey version and retry
        run: |
            choco upgrade chocolatey --version=2.3.0
            choco install htmlhelp-workshop -y


       
